[package]
name = "AssetManager"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.11.0"
actix-multipart = "0.6"
futures-util = "0.3"
serde = "1.0.219"
serde_json = "1.0.140"
sanitize-filename = "0.6.0"
mysql = "26.0.0"
